title: 我的个人主页
description: 个人主页 & 知识库
baseurl: ""
url: https://github.com/en-o/blog

# 集合配置
collections:
  docs:
    output: true
    permalink: /docs/:path/

# 默认设置
defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: doc
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 构建设置
markdown: kramdown

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - blog.sh
  - jekyll_personal_site.md
  - jekyll_preview.html
  - admin/                    # 排除管理平台
